### USER ROUTES ###
### LOGIN USER
POST http://localhost:3001/login
Content-Type: application/json

{
  "id": 3914,
  "password": "password"
}

### GET ALL USERS (isAuthenticated)
GET http://localhost:3001/users
Content-Type: application/json

{
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0NSwiZmlyc3RuYW1lIjoiQ2xhcmsiLCJsYXN0bmFtZSI6IktlbnQiLCJpc19hZG1pbiI6ZmFsc2UsImlhdCI6MTYxNjY2NDYxNH0.CLD_rFCFQYKQto5v12Tj0yIOnuyttj8QeEormGypVaY"
}

### GET SINGLE USER (ensureLoggedIn/admin)
GET http://localhost:3001/users/1234
Content-Type: application/json

# ADMIN TOKEN
{
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQ1NiwiZmlyc3RuYW1lIjoiTXVoYW1tYWQiLCJsYXN0bmFtZSI6IkFsaSIsImlzX2FkbWluIjp0cnVlLCJpYXQiOjE2MTY2NjQ1NjZ9.iwdY3E1pdoGL4qm9hnJoeKjNKJyUXF6VqV9AkaVC-Kk"
 }

# # USER TOKEN
# {
#   "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIzNCwiZmlyc3RuYW1lIjoiSm9obiIsImxhc3RuYW1lIjoiQ29ubmVyIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE2MTY2OTc4MDB9.CX8TTZe84r57kS8O7NwcPwbAJMT7arfex8LWmXmNAjA"
#  }


### ADD NEW USER 
POST http://localhost:3001/users
Content-Type: application/json

{
  "id": 1111,
  "password": "password",
  "firstname": "John",
  "lastname": "Conner",
  "is_admin": true
}


### UPDATE USER (ADMIN PRIVELAGE REQUIRED)
PATCH http://localhost:3001/users/9999
Content-Type: application/json

{
  "password": "password",
  "is_admin": true,
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMSwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IlVzZXIiLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2NjY0MjQwfQ.w_6qrKqKrBUhzs6QF7HrxWTs8o97vuzDlPO-P8FTHU4"
}


### DELETE USER (EXTREME CAUTION) (isAdmin/ensureLoggedIn)
DELETE http://localhost:3001/users/7777
Content-Type: application/json

# ADMIN TOKEN
{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMSwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IlVzZXIiLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2NjY0MjQwfQ.w_6qrKqKrBUhzs6QF7HrxWTs8o97vuzDlPO-P8FTHU4"
}

# USER TOKEN
# {
#   "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0NSwiZmlyc3RuYW1lIjoiQ2xhcmsiLCJsYXN0bmFtZSI6IktlbnQiLCJpc19hZG1pbiI6ZmFsc2UsImlhdCI6MTYxNjY2NDYxNH0.CLD_rFCFQYKQto5v12Tj0yIOnuyttj8QeEormGypVaY"
# }

### PHYSICIAN ROUTES ###
### GET ALL PHYSICIANS
GET http://localhost:3001/physicians
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0NSwiZmlyc3RuYW1lIjoiQ2xhcmsiLCJsYXN0bmFtZSI6IktlbnQiLCJpc19hZG1pbiI6ZmFsc2UsImlhdCI6MTYxNjY2NDYxNH0.CLD_rFCFQYKQto5v12Tj0yIOnuyttj8QeEormGypVaY"
}

### ADD A PHYSICIAN
POST http://localhost:3001/physicians
Content-Type: application/json

{
  "firstname": "Roaa",
  "lastname": "AlKhallaf",
  "department_id": 1,
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMSwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IlVzZXIiLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2NjY0MjQwfQ.w_6qrKqKrBUhzs6QF7HrxWTs8o97vuzDlPO-P8FTHU4"
}


### DELETE A PHYSICIAN
DELETE http://localhost:3001/physicians/14
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njc4OSwiZmlyc3RuYW1lIjoiUGV0ZXIiLCJsYXN0bmFtZSI6IlBhcmtlciIsImlhdCI6MTYxNTI4MDA4N30.ciR81HBgyin2VXKLDvOcbeWR2K5lBz2FIk71EQqvrFo"
}

### DEPARTMENT/LOCATION/PROCEDURE/TESTS ROUTES ###
GET http://localhost:3001/hospital/departments
Content-Type: application/json

# USER TOKEN
{
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0NSwiZmlyc3RuYW1lIjoiQ2xhcmsiLCJsYXN0bmFtZSI6IktlbnQiLCJpc19hZG1pbiI6ZmFsc2UsImlhdCI6MTYxNjY5ODA0OX0.4_gTAwv1lbKfJwGyt44CPlUiy6qJNiMlWI9Ry4dixlo"
}

### ADD HOSPITAL DATA 
POST http://localhost:3001/hospital/procedures
Content-Type: application/json

{
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMSwiZmlyc3RuYW1lIjoiSm9obiIsImxhc3RuYW1lIjoiQ29ubmVyIiwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTYyMjU3MTQyMX0.2Vkf-5t3D0Gp2AlSpUs1eK0okERWuJATvLOtf0GlGr0",
  "procedure_name": "SFEMG"
}

### DELETE HOSPITAL DATA 
DELETE http://localhost:3001/hospital/testcodes/
Content-Type: application/json

# ADMIN TOKEN
{
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMSwiZmlyc3RuYW1lIjoiSm9obiIsImxhc3RuYW1lIjoiQ29ubmVyIiwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTYyMjU3MTQyMX0.2Vkf-5t3D0Gp2AlSpUs1eK0okERWuJATvLOtf0GlGr0"
}

# USER TOKEN
# {
#   "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzkxNCwiZmlyc3RuYW1lIjoiRGVuemlsIiwibGFzdG5hbWUiOiJUYXVybyIsImlzX2FkbWluIjpmYWxzZSwiaWF0IjoxNjIyNTcyMTM5fQ.GnHJcOF7rrY7BegSzEXKeCKc01B1t7yx9M6k_j8dw88"
# }



### PATIENT ROUTES ###
### FIND ALL PATIENTS
GET http://localhost:3001/patients/2348
Content-Type: application/json

{
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM0NSwiZmlyc3RuYW1lIjoiQ2xhcmsiLCJsYXN0bmFtZSI6IktlbnQiLCJpc19hZG1pbiI6ZmFsc2UsImlhdCI6MTYxNjY2NDYxNH0.CLD_rFCFQYKQto5v12Tj0yIOnuyttj8QeEormGypVaY"
}

### ADD NEW PATIENT
POST http://localhost:3001/patients/
Content-Type: application/json

# {
#   "mrn": 667543,
#   "firstname": "Peter",
#   "lastname": "Parker",
#   "dob": "1990-07-13",
#   "gender": "male",
#   "age_category": "pediatric",
#   "nationality": "Egyptian"
# }

{
  "mrn": 123456,
  "firstname": "John",
  "lastname": "Conner",
  "dob": "2012-04-23",
  "gender": "male",
  "age_group": "adult",
  "nationality": "Saudi"
}

### FIND PATIENT BY MRN
GET http://localhost:3001/patients/2348
Content-Type: application/json

{
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njc4OSwiZmlyc3RuYW1lIjoiUGV0ZXIiLCJsYXN0bmFtZSI6IlBhcmtlciIsImlhdCI6MTYxNTI3NTYyMn0.DPsqDbgtNhDKqarnRQe8VPq_1uUi0xsdiODGch2wUvY"
}

### UPDATE A SINGLE PATIENT
PATCH http://localhost:3001/patients/2348
Content-Type: application/json


### ADD VISIT
POST http://localhost:3001/visitdetails/21-234
Content-Type: application/json

{
  "visit_id": "21-234",
  "test_id": 3,
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIyMiwiZmlyc3RuYW1lIjoiQmlsYWwiLCJsYXN0bmFtZSI6IkFiZHVsUWFkaXIiLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjIwOTg3ODY2fQ.fQtueCNt6Otq9H7117uC5sRM0MWAFUS8s66lXmyrH60"
}

### GET Visit
GET http://localhost:3001/visits/21-413
Content-Type: application/json

{
  "_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIyMiwiZmlyc3RuYW1lIjoiQmlsYWwiLCJsYXN0bmFtZSI6IkFiZHVsUWFkaXIiLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjIwOTg3ODY2fQ.fQtueCNt6Otq9H7117uC5sRM0MWAFUS8s66lXmyrH60"
  
}